DIRECTION_UP =3D 0
DIRECTION_DOWN =3D 1
DIRECTION_LEFT =3D 2
DIRECTION_RIGHT =3D 3

from events import *

#------------------------------------------------------------------------=
------
class EventManager:
	"""this object is responsible for coordinating most communication
	between the Model, View, and Controller."""
	def __init__(self):
		from weakref import WeakKeyDictionary
		self.listeners =3D WeakKeyDictionary()
		self.eventQueue=3D []
		self.listenersToAdd =3D []
		self.listenersToRemove =3D []

	#----------------------------------------------------------------------
	def RegisterListener( self, listener ):
		self.listenersToAdd.append(listener)

	#----------------------------------------------------------------------
	def ActuallyUpdateListeners(self):
		for listener in self.listenersToAdd:
			self.listeners[ listener ] =3D 1
		for listener in self.listenersToRemove:
			if listener in self.listeners:
				del self.listeners[ listener ]

	#----------------------------------------------------------------------
	def UnregisterListener( self, listener ):
		self.listenersToRemove.append(listener)
	=09
	#----------------------------------------------------------------------
	def Post( self, event ):
		self.eventQueue.append(event)
		if isinstance(event, TickEvent):
			# Consume the event queue every Tick.
			self.ActuallyUpdateListeners()
			self.ConsumeEventQueue()
		else:
			Debug( "     Message: " + event.name )

	#----------------------------------------------------------------------
	def ConsumeEventQueue(self):
		i =3D 0
		while i &lt; len( self.eventQueue ):
			event =3D self.eventQueue[i]
			for listener in self.listeners:
				# Note: a side effect of notifying the listener
				# could be that more events are put on the queue
				# or listeners could Register / Unregister
				old =3D len(self.eventQueue)
				listener.Notify( event )
			i +=3D 1
			if self.listenersToAdd:
				self.ActuallyUpdateListeners()
		#all code paths that could possibly add more events to=20
		# the eventQueue have been exhausted at this point, so=20
		# it's safe to empty the queue
		self.eventQueue=3D []


#------------------------------------------------------------------------=
------
class KeyboardController:
	"""KeyboardController takes Pygame events generated by the
	keyboard and uses them to control the model, by sending Requests
	or to control the Pygame display directly, as with the QuitEvent
	"""
	def __init__(self, evManager, playerName=3DNone):
		'''playerName is an optional argument; when given, this
		keyboardController will control only the specified player
		'''
		self.evManager =3D evManager
		self.evManager.RegisterListener( self )

		self.activePlayer =3D None
		self.playerName =3D playerName
		self.players =3D []

	#----------------------------------------------------------------------
	def Notify(self, event):
		if isinstance( event, PlayerJoinEvent ):
			self.players.append( event.player )
			if event.player.name =3D=3D self.playerName:
				self.activePlayer =3D event.player
			if not self.playerName and not self.activePlayer:
				self.activePlayer =3D event.player

		if isinstance( event, GameSyncEvent ):
			game =3D event.game
			self.players =3D game.players[:] # copy the list
			if self.playerName and self.players:
				self.activePlayer =3D [p for p in self.players
				              if p.name =3D=3D self.playerName][0]

		if isinstance( event, TickEvent ):
			#Handle Input Events
			for event in pygame.event.get():
				ev =3D None
				if event.type =3D=3D QUIT:
					ev =3D QuitEvent()
				elif event.type =3D=3D KEYDOWN \
				     and event.key =3D=3D K_ESCAPE:
					ev =3D QuitEvent()
				elif event.type =3D=3D KEYDOWN \
				     and event.key =3D=3D K_p:
					import random
					rng =3D random.Random()
					name =3D str( rng.randrange(1,100) )
					if self.playerName:
						name =3D self.playerName
					playerData =3D {'name':name}
					ev =3D PlayerJoinRequest(playerData)

				elif event.type =3D=3D KEYDOWN \
				     and event.key =3D=3D K_o:
					self.activePlayer =3D self.players[1]
					self.players.reverse()

				elif event.type =3D=3D KEYDOWN \
				     and event.key =3D=3D K_c:
					if not self.activePlayer:
						continue
					charactor, sector =3D self.activePlayer.GetPlaceData()
					ev =3D CharactorPlaceRequest(=20
					  self.activePlayer,=20
					  charactor,
					  sector )

				elif event.type =3D=3D KEYDOWN \
				     and event.key =3D=3D K_UP:
					if not self.activePlayer:
						continue
					direction =3D DIRECTION_UP
					data =3D self.activePlayer.GetMoveData()
					ev =3D CharactorMoveRequest(=20
					  self.activePlayer,=20
					  data[0],=20
					  direction )

				elif event.type =3D=3D KEYDOWN \
				     and event.key =3D=3D K_DOWN:
					if not self.activePlayer:
						continue
					direction =3D DIRECTION_DOWN
					data =3D self.activePlayer.GetMoveData()
					ev =3D CharactorMoveRequest(=20
					  self.activePlayer,=20
					  data[0],=20
					  direction )

				elif event.type =3D=3D KEYDOWN \
				     and event.key =3D=3D K_LEFT:
					if not self.activePlayer:
						continue
					direction =3D DIRECTION_LEFT
					data =3D self.activePlayer.GetMoveData()
					ev =3D CharactorMoveRequest(=20
					  self.activePlayer,=20
					  data[0],=20
					  direction )

				elif event.type =3D=3D KEYDOWN \
				     and event.key =3D=3D K_RIGHT:
					if not self.activePlayer:
						continue
					direction =3D DIRECTION_RIGHT
					data =3D self.activePlayer.GetMoveData()
					ev =3D CharactorMoveRequest(=20
					  self.activePlayer,=20
					  data[0],=20
					  direction )

				elif event.type =3D=3D KEYDOWN:
					ev =3D GameStartRequest()

				if ev:
					self.evManager.Post( ev )


#------------------------------------------------------------------------=
------
class CPUSpinnerController:
	"""..."""
	def __init__(self, evManager):
		self.evManager =3D evManager
		self.evManager.RegisterListener( self )

		self.keepGoing =3D 1

	#----------------------------------------------------------------------
	def Run(self):
		while self.keepGoing:
			event =3D TickEvent()
			self.evManager.Post( event )

	#----------------------------------------------------------------------
	def Notify(self, event):
		if isinstance( event, QuitEvent ):
			#this will stop the while loop from running
			self.keepGoing =3D False


import pygame
from pygame.locals import *

#------------------------------------------------------------------------=
------
class StatusBarSprite(pygame.sprite.Sprite):
	def __init__(self, evManager, group=3DNone):
		pygame.sprite.Sprite.__init__(self, group)

		self.evManager =3D evManager
		self.evManager.RegisterListener( self )

		self.font =3D pygame.font.Font(None, 30)
		self.text =3D '.'
		self.image =3D self.font.render( self.text, 1, (255,0,0))
		self.rect  =3D self.image.get_rect()
		self.rect.move_ip( (0, 414) )

	#----------------------------------------------------------------------
	def update(self):
		self.image =3D self.font.render( self.text, 1, (255,0,0))
		self.rect  =3D self.image.get_rect()
		self.rect.move_ip( (0, 414) )

	#----------------------------------------------------------------------
	def Notify(self, event):
		if not isinstance( event, TickEvent ):
			self.text =3D event.name

#------------------------------------------------------------------------=
------
class SectorSprite(pygame.sprite.Sprite):
	def __init__(self, sector, group=3DNone):
		pygame.sprite.Sprite.__init__(self, group)
		self.image =3D pygame.Surface( (128,128) )
		self.image.fill( (0,255,128) )

		self.sector =3D sector

#------------------------------------------------------------------------=
------
class CharactorSprite(pygame.sprite.Sprite):
	counter =3D 0
	def __init__(self, charactor, group=3DNone, color=3D(0,0,0)):
		pygame.sprite.Sprite.__init__(self, group)

		charactorSurf =3D pygame.Surface( (64,64) )
		charactorSurf =3D charactorSurf.convert_alpha()
		charactorSurf.fill((0,0,0,0)) #make transparent
		pygame.draw.circle( charactorSurf, color, (32,32), 32 )
		self.image =3D charactorSurf
		self.rect  =3D charactorSurf.get_rect()

		self.order =3D CharactorSprite.counter
		CharactorSprite.counter +=3D 1

		self.charactor =3D charactor
		self.moveTo =3D None

	#----------------------------------------------------------------------
	def update(self):
		if self.moveTo:
			self.rect.center =3D self.moveTo
			self.moveTo =3D None
			# offset the rect so that charactors don't draw exactly on
			# top of each other.
			self.rect.move_ip(self.order, self.order)

#------------------------------------------------------------------------=
------
class PygameView:
	def __init__(self, evManager):
		self.evManager =3D evManager
		self.evManager.RegisterListener( self )

		self.charactorColors =3D [ (255,0,0), (0,0,255) ]

		pygame.init()
		self.window =3D pygame.display.set_mode( (424,440) )
		pygame.display.set_caption( 'Example Game' )
		self.background =3D pygame.Surface( self.window.get_size() )
		self.background.fill( (0,0,0) )
		font =3D pygame.font.Font(None, 30)
		text =3D """Press SPACE BAR to start"""
		textImg =3D font.render( text, 1, (255,0,0))
		self.background.blit( textImg, (0,0) )
		text =3D """      P for new player"""
		textImg =3D font.render( text, 1, (255,0,0))
		self.background.blit( textImg, (0,1*font.get_linesize()) )
		text =3D """      C for new charactor"""
		textImg =3D font.render( text, 1, (255,0,0))
		self.background.blit( textImg, (0,2*font.get_linesize()) )
		text =3D """      O to switch players"""
		textImg =3D font.render( text, 1, (255,0,0))
		self.background.blit( textImg, (0,3*font.get_linesize()) )

		self.window.blit( self.background, (0,0) )
		pygame.display.flip()

		self.backSprites =3D pygame.sprite.RenderUpdates()
		self.frontSprites =3D pygame.sprite.RenderUpdates()


	#----------------------------------------------------------------------
	def ShowMap(self, gameMap):
		# clear the screen first
		self.background.fill( (0,0,0) )
		self.window.blit( self.background, (0,0) )
		pygame.display.flip()

		# use this squareRect as a cursor and go through the
		# columns and rows and assign the rect=20
		# positions of the SectorSprites
		squareRect =3D pygame.Rect( (-128,10, 128,128 ) )

		column =3D 0
		for sector in gameMap.sectors:
			if column &lt; 3:
				squareRect =3D squareRect.move( 138,0 )
			else:
				column =3D 0
				squareRect =3D squareRect.move( -(138*2), 138 )
			column +=3D 1
			newSprite =3D SectorSprite( sector, self.backSprites )
			newSprite.rect =3D squareRect
			newSprite =3D None

		statusBarSprite =3D StatusBarSprite(self.evManager,self.backSprites)

	#----------------------------------------------------------------------
	def ShowCharactor(self, charactor):
		sector =3D charactor.sector
		if not sector:
			print "Charactor is not in a sector.  cannot show"
			return

		charactorSprite =3D self.GetCharactorSprite( charactor )
		if not charactorSprite:
			charactorSprite =3D CharactorSprite( self.frontSprites )
		sectorSprite =3D self.GetSectorSprite( sector )
		charactorSprite.rect.center =3D sectorSprite.rect.center

	#----------------------------------------------------------------------
	def MoveCharactor(self, charactor):
		charactorSprite =3D self.GetCharactorSprite( charactor )

		sector =3D charactor.sector
		sectorSprite =3D self.GetSectorSprite( sector )

		charactorSprite.moveTo =3D sectorSprite.rect.center

	#----------------------------------------------------------------------
	def GetCharactorSprite(self, charactor):
		#there will be only one
		for s in self.frontSprites:
			if s.charactor is charactor:
				return s

		col =3D self.charactorColors[0]
		print "new color: ", col
		self.charactorColors.reverse()
		return CharactorSprite(charactor, self.frontSprites, col)

	#----------------------------------------------------------------------
	def GetSectorSprite(self, sector):
		for s in self.backSprites:
			if hasattr(s, "sector") and s.sector =3D=3D sector:
				return s


	#----------------------------------------------------------------------
	def Notify(self, event):
		if isinstance( event, TickEvent ):
			#Draw Everything
			self.backSprites.clear( self.window, self.background )
			self.frontSprites.clear( self.window, self.background )

			self.backSprites.update()
			self.frontSprites.update()

			dirtyRects1 =3D self.backSprites.draw( self.window )
			dirtyRects2 =3D self.frontSprites.draw( self.window )
		=09
			dirtyRects =3D dirtyRects1 + dirtyRects2
			pygame.display.update( dirtyRects )


		elif isinstance( event, MapBuiltEvent ):
			gameMap =3D event.map
			self.ShowMap( gameMap )

		elif isinstance( event, CharactorPlaceEvent ):
			self.ShowCharactor( event.charactor )

		elif isinstance( event, CharactorMoveEvent ):
			self.MoveCharactor( event.charactor )

		elif isinstance( event, GameSyncEvent ):
			print 'Pygame View syncing to game state', event, event.game.__dict__
			game =3D event.game
			if game.state =3D=3D Game.STATE_PREPARING:
				return
			self.ShowMap( game.map )
			for player in game.players:
				for charactor in player.charactors:
					self.ShowCharactor( charactor )

#------------------------------------------------------------------------=
------
class Game:
	"""..."""

	STATE_PREPARING =3D 'preparing'
	STATE_RUNNING =3D 'running'
	STATE_PAUSED =3D 'paused'

	#----------------------------------------------------------------------
	def __init__(self, evManager):
		self.evManager =3D evManager
		self.evManager.RegisterListener( self )

		self.state =3D Game.STATE_PREPARING
	=09
		self.players =3D [ ]
		self.maxPlayers =3D 2
		self.map =3D Map( evManager )

	#----------------------------------------------------------------------
	def Start(self):
		self.map.Build()
		self.state =3D Game.STATE_RUNNING
		ev =3D GameStartedEvent( self )
		self.evManager.Post( ev )

	#----------------------------------------------------------------------
	def AddPlayer(self, player):
		self.players.append( player )
		player.SetGame( self )
		ev =3D PlayerJoinEvent( player )
		self.evManager.Post( ev )


	#----------------------------------------------------------------------
	def Notify(self, event):
		if isinstance( event, GameStartRequest ):
			if self.state =3D=3D Game.STATE_PREPARING:
				self.Start()

		if isinstance( event, PlayerJoinRequest ):
			if self.state !=3D Game.STATE_PREPARING:
				print "Players can not join after Game start"
				return
			if len(self.players) &gt;=3D self.maxPlayers:
				print "Maximum players already joined"
				return
			player =3D Player( self.evManager )
			player.SetData( event.playerDict )
			self.AddPlayer( player )


#------------------------------------------------------------------------=
------
class Player(object):
	"""..."""
	def __init__(self, evManager):
		self.evManager =3D evManager
		self.game =3D None
		self.name =3D ""
		self.evManager.RegisterListener( self )

		self.charactors =3D [ Charactor(evManager) ]

	#----------------------------------------------------------------------
	def __str__(self):
		return '&lt;Player %s %s&gt;' % (self.name, id(self))

	#----------------------------------------------------------------------
	def GetPlaceData( self ):
		charactor =3D self.charactors[0]
		gameMap =3D self.game.map
		sector =3D  gameMap.sectors[gameMap.startSectorIndex]
		return [charactor, sector]

	#----------------------------------------------------------------------
	def GetMoveData( self ):
		return [self.charactors[0]]

	#----------------------------------------------------------------------
	def SetGame( self, game ):
		self.game =3D game

	#----------------------------------------------------------------------
	def SetData( self, playerDict ):
		self.name =3D playerDict['name']

	#----------------------------------------------------------------------
	def Notify(self, event):
		pass
		#if isinstance( event, PlayerJoinEvent):
			#if event.player is self:

#------------------------------------------------------------------------=
------
class Charactor:
	"""..."""

	STATE_INACTIVE =3D 0
	STATE_ACTIVE =3D 1

	def __init__(self, evManager):
		self.evManager =3D evManager
		self.evManager.RegisterListener( self )

		self.sector =3D None
		self.state =3D Charactor.STATE_INACTIVE

	#----------------------------------------------------------------------
	def __str__(self):
		return '&lt;Charactor %s&gt;' % id(self)

	#----------------------------------------------------------------------
	def Move(self, direction):
		if self.state =3D=3D Charactor.STATE_INACTIVE:
			return

		if self.sector.MovePossible( direction ):
			newSector =3D self.sector.neighbors[direction]
			self.sector =3D newSector
			ev =3D CharactorMoveEvent( self )
			self.evManager.Post( ev )

	#----------------------------------------------------------------------
	def Place(self, sector):
		self.sector =3D sector
		self.state =3D Charactor.STATE_ACTIVE

		ev =3D CharactorPlaceEvent( self )
		self.evManager.Post( ev )

	#----------------------------------------------------------------------
	def Notify(self, event):
		if isinstance( event, CharactorPlaceRequest ) \
		 and event.charactor =3D=3D self:
			self.Place( event.sector )

		elif isinstance( event, CharactorMoveRequest ) \
		  and event.charactor =3D=3D self:
			self.Move( event.direction )

#------------------------------------------------------------------------=
------
class Map:
	"""..."""

	STATE_PREPARING =3D 0
	STATE_BUILT =3D 1


	#----------------------------------------------------------------------
	def __init__(self, evManager):
		self.evManager =3D evManager
		#self.evManager.RegisterListener( self )

		self.state =3D Map.STATE_PREPARING

		self.sectors =3D []
		self.startSectorIndex =3D 0

	#----------------------------------------------------------------------
	def Build(self):
		for i in range(9):
			self.sectors.append( Sector(self.evManager) )

		self.sectors[3].neighbors[DIRECTION_UP] =3D self.sectors[0]
		self.sectors[4].neighbors[DIRECTION_UP] =3D self.sectors[1]
		self.sectors[5].neighbors[DIRECTION_UP] =3D self.sectors[2]
		self.sectors[6].neighbors[DIRECTION_UP] =3D self.sectors[3]
		self.sectors[7].neighbors[DIRECTION_UP] =3D self.sectors[4]
		self.sectors[8].neighbors[DIRECTION_UP] =3D self.sectors[5]

		self.sectors[0].neighbors[DIRECTION_DOWN] =3D self.sectors[3]
		self.sectors[1].neighbors[DIRECTION_DOWN] =3D self.sectors[4]
		self.sectors[2].neighbors[DIRECTION_DOWN] =3D self.sectors[5]
		self.sectors[3].neighbors[DIRECTION_DOWN] =3D self.sectors[6]
		self.sectors[4].neighbors[DIRECTION_DOWN] =3D self.sectors[7]
		self.sectors[5].neighbors[DIRECTION_DOWN] =3D self.sectors[8]

		self.sectors[1].neighbors[DIRECTION_LEFT] =3D self.sectors[0]
		self.sectors[2].neighbors[DIRECTION_LEFT] =3D self.sectors[1]
		self.sectors[4].neighbors[DIRECTION_LEFT] =3D self.sectors[3]
		self.sectors[5].neighbors[DIRECTION_LEFT] =3D self.sectors[4]
		self.sectors[7].neighbors[DIRECTION_LEFT] =3D self.sectors[6]
		self.sectors[8].neighbors[DIRECTION_LEFT] =3D self.sectors[7]

		self.sectors[0].neighbors[DIRECTION_RIGHT] =3D self.sectors[1]
		self.sectors[1].neighbors[DIRECTION_RIGHT] =3D self.sectors[2]
		self.sectors[3].neighbors[DIRECTION_RIGHT] =3D self.sectors[4]
		self.sectors[4].neighbors[DIRECTION_RIGHT] =3D self.sectors[5]
		self.sectors[6].neighbors[DIRECTION_RIGHT] =3D self.sectors[7]
		self.sectors[7].neighbors[DIRECTION_RIGHT] =3D self.sectors[8]

		self.state =3D Map.STATE_BUILT

		ev =3D MapBuiltEvent( self )
		self.evManager.Post( ev )

#------------------------------------------------------------------------=
------
class Sector:
	"""..."""
	def __init__(self, evManager):
		self.evManager =3D evManager
		#self.evManager.RegisterListener( self )

		self.neighbors =3D range(4)

		self.neighbors[DIRECTION_UP] =3D None
		self.neighbors[DIRECTION_DOWN] =3D None
		self.neighbors[DIRECTION_LEFT] =3D None
		self.neighbors[DIRECTION_RIGHT] =3D None

	#----------------------------------------------------------------------
	def MovePossible(self, direction):
		if self.neighbors[direction]:
			return 1


#------------------------------------------------------------------------=
------
def main():
	"""..."""
	evManager =3D EventManager()

	keybd =3D KeyboardController( evManager )
	spinner =3D CPUSpinnerController( evManager )
	pygameView =3D PygameView( evManager )
	game =3D Game( evManager )
=09
	spinner.Run()

if __name__ =3D=3D "__main__":
	main()
</PRE></BODY></HTML>
